env:
  browser: true
  es2021: true
root: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
settings: {
  react: {
    version: detect
  }
}  
rules: {
  'semi': 'off',
  'indent': 'off',
  'eol-last': ['warn', 'never'],
  '@typescript-eslint/semi': ['warn', 'always'],
  '@typescript-eslint/indent': ['warn', 2],
  '@typescript-eslint/no-floating-promises': ['warn'],
  '@typescript-eslint/strict-boolean-expressions': ['warn'],
  '@typescript-eslint/triple-slash-reference': ['warn'],
  '@typescript-eslint/explicit-function-return-type': ['warn'],
  '@typescript-eslint/consistent-type-definitions': ['warn'],
  '@typescript-eslint/return-await': ['warn'],
  '@typescript-eslint/space-before-function-paren': ['warn'],
  '@typescript-eslint/restrict-template-expressions': ['warn'],
  'no-trailing-spaces': 'off',
  no-return-assign: ['warn'],
  operator-linebreak: ['warn'],
  react/jsx-tag-spacing: ['warn'],
  react/prop-types: ['warn'],
  react/display-name: ['warn'],
  '@typescript-eslint/no-unused-vars': ['warn'],
  '@typescript-eslint/no-unused-expressions': ['warn'],
  'react/react-in-jsx-scope': ['warn'],
  'no-mixed-spaces-and-tabs': ['warn'],
  'import/export': ['warn'],
  'no-tabs': ['warn'],
  '@typescript-eslint/no-var-requires': ['warn'],
  '@typescript-eslint/restrict-plus-operands': ['warn'],
}