env:
  browser: true
  es2021: true
root: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
settings: {
  react: {
    version: detect
  }
}  
rules: {
  'semi': 'off',
  'indent': 'off',
  'eol-last': ['warn', 'never'],
  '@typescript-eslint/semi': ['warn', 'always'],
  '@typescript-eslint/indent': ['warn', 2],
  '@typescript-eslint/no-floating-promises': ['warn'],
  '@typescript-eslint/strict-boolean-expressions': ['warn'],
  '@typescript-eslint/triple-slash-reference': ['warn'],
  '@typescript-eslint/explicit-function-return-type': ['warn'],
  '@typescript-eslint/consistent-type-definitions': ['warn'],
  '@typescript-eslint/return-await': ['warn'],
  '@typescript-eslint/space-before-function-paren': ['warn'],
  '@typescript-eslint/restrict-template-expressions': ['warn'],
  'no-trailing-spaces': 'off',
  '@typescript-eslint/array-type': ['warn'],
  '@typescript-eslint/keyword-spacing': ['warn'],
  '@typescript-eslint/lines-between-class-members': ['warn'],
  '@typescript-eslint/member-delimiter-style': ['warn'],
  '@typescript-eslint/no-unused-expressions': ['warn'],
  '@typescript-eslint/no-unused-vars': ['warn'],
  '@typescript-eslint/no-var-requires': ['warn'],
  '@typescript-eslint/promise-function-async': ['warn'],
  '@typescript-eslint/quotes': ['warn'],
  '@typescript-eslint/restrict-plus-operands': ['warn'],
  '@typescript-eslint/type-annotation-spacing': ['warn'],
  'arrow-spacing': ['warn'],
  'comma-dangle': ['warn'],
  'curly': ['warn'],
  'import/export': ['warn'],
  'key-spacing': ['warn'],
  'multiline-ternary': ['warn'],
  'no-mixed-spaces-and-tabs': ['warn'],
  'no-multi-spaces': ['warn'],
  'no-multiple-empty-lines': ['warn'],
  'no-return-assign': ['warn'],
  'no-tabs': ['warn'],
  'no-unneeded-ternary': ['warn'],
  'object-curly-spacing': ['warn'],
  'operator-linebreak': ['warn'],
  'padded-blocks': ['warn'],
  'prefer-const': ['warn'],
  'react/display-name': ['warn'],
  'react/jsx-tag-spacing': ['warn'],
  'react/prop-types': ['warn'],
  'react/react-in-jsx-scope': ['warn'],
  'space-before-blocks': ['warn'],
  'space-infix-ops': ['warn'],
  'spaced-comment': ['warn'],
  'quotes': ['warn']
}