version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      # install dependencies
      - npm install

  build:
    commands:
      # run build script
      - npm run-script build

artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - '**/*'
  base-directory: 'build'