name: Run Linter and Tests on Push

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Use the Node.js version you need

    - name: Install dependencies
      run: |
        npm install -g create-react-app
        npm i @material-ui/lab
        
    - name: Run Linter
      run: |
        npm run lint > lint-results.txt
        
    - name: Convert Linter Errors to Annotations
      uses: actions/github-script@0.10.0
      with:
        script: |
          const fs = require('fs');
          const lintResults = fs.readFileSync('lint-results.txt', 'utf-8');
          const annotations = lintResults.split('\n').map(line => {
            const parts = line.split(':');
            return {
              file: parts[0],
              start_line: parseInt(parts[1], 10),
              end_line: parseInt(parts[1], 10),
              annotation_level: 'warning',
              message: parts[2],
            };
          });
          await github.checks.create({
            ...context.repo,
            check_run_id: context.payload.check_run.id,
            output: {
              title: 'Linting Warnings',
              summary: 'Linting warnings found in the code.',
              annotations,
            },
          });
        
    - name: Run Tests
      run: |
        npm test
