name: Run Tests on Push

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Use the Node.js version you need

    - name: Install dependencies
      run: |
        npm install -g create-react-app
        npm i @material-ui/lab

    - name: Run Tests
      run: |
        npm test
